language: node_js
node_js: lts/*
env:
  global:
  - secure: PAfRjaqWSfZzGuP/SfxQ32gymWOhIL+aaURyJWQmJ6uKHSvIla38ExYYUuSFjMJ1W37lhGbouDwbIL5fQCscApvnOHtgNdpA6aQBNKXuQPJ5LSV4HglfHmu8IUaQfrMOPahRdDaXGmgyH8/kghL2ufpy5pq67Q1n9323zeGTR0Tnn2qmMFMee/kkV6oJS3on8pYn99viybRvsPRUb2aw0t5oASz3OjUz52R8hSzcQFrmJUR+2wQ6kGFOtolNC8mvedhzAAfdmWHVHthiXV0BsfvHUclcY4iTBsTDaxXanjIatDTtQKoz/C5JehffJXRgtW647CN29fLTDqFTLU08pnZUoY9yzmna+AyS3hLHPDc9D5OrDy5mChWahqrdq4JhrUVKGYtx2MilwAyvF+0cHiUlwNfeJHRLERke8Ep7l8rVBt9CRaZVsuRgU8dwVojWVyYvpQaBvm3hHMkOwDL4ySYCQuN0hhUCwhN81pByCUtPF2OomLx4BOTc8hxZHpZScT3GRw0zXyM1ur3ymt5ILQlkUgyYjocAEG2ZI1ROLGqG/AV8f5cAX8k3zWyCf1CPTDQfOZuM2Oi6JezJPuSSeQkQrYSuGvFQhAmV6CVwCm7ifAp5vUphc8xamu71EEpXOAnKVMKiUXGe+3BHrXh6TxZ5wADvPvcPnN1cClIEQTY=
services:
- docker
script:
- npm run lint
- docker build -t danigatunes/pixelroom .
deploy:
  on:
    branch: master
  provider: script
  script: echo ${DOCKER_PASSWORD} | docker login -u danigatunes --password-stdin && docker push danigatunes/pixelroom  
  skip_cleanup: true
